### ISSUE TITLE
Can we decouple PJ_CONTEXT from PJ, API-wise?

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#1222]
This is somewhat related to suggestion #1047, by @xylosper, although contrary to #1047 this item is designed to maintain backwards compatibility. 

The PROJ contexts are intended as per-thread items, originally (mistakenly) introduced to support per-thread errno.

The existing API includes the current context as argument, hence leaving it to the user to ensure that the correct context is passed:

    proj_create (PJ_CONTEXT *ctx, const char *definition);

With the introduction of C++11 as programming platform, we have native support for thread local variables using the `thread_local` storage class.

Wouldn’t it be neat to introduce a thread local context, and remove the `PJ_CONTEXT` argument from new API PROJ.6 entries - and perhaps modify the old API entries to ignore whatever context is passed, and obtain the correct context from an API call (perhaps by making `proj_context_create()` return the thread local context if it exists, otherwise create it).

This would make it impossible to provide a context from a different thread, it would decouple contexts from PJs, and it would simplify the API a bit.

Sketchy implementation example:

    extern thread_local PJ_CONTEXT *ctx;
    
    PJ *proj6_create (const char *definition) {
        return proj_create (proj_context_create(), definition);
    }

**Comment by rouault** [comment]
I implemented a TLS strategy in my gdalbarn GDAL branch to manage PROJ contexts, but should we really impose that on all PROJ users ?

Having the PROJ context available is handly to be able to set parameters on it like proj_context_set_file_finder(), proj_context_set_search_paths(), proj_context_set_database_path(), etc.

By the way: if we follow the road you suggest, we should make sure to no longer store a PJ_CONTEXT  in struct PJ (for the use cases where a PJ object is created by one thread, and later transfered to another one)

**Comment by busstoptaktik** [comment]
> I implemented a TLS strategy in my gdalbarn GDAL branch to manage PROJ contexts, but should we really impose that on all PROJ users ?

IMHO that **would** be a fine idea, especially since it has been no secret that contexts are intended as a clumsy way of ensuring thread locality, later extended with the fileapi material (which then, by propagation, is thread local as well).

**In practice, however,** we will need to maintain some backwards compatibility - hence the proj6_ namespace above (actually I think introducing a new namespace would be a bad idea - rather I would use separate API entries in the same namespace).

So separate entries, perhaps supplemented by the convention that passing a 0 for context leads you to the thread_local ctx, rather than a global as today.

> By the way: if we follow the road you suggest, we should make sure to no longer store a PJ_CONTEXT in struct PJ (for the use cases where a PJ object is created by one thread, and later transfered to another one)

I cannot remember why we did that, but I think the use case you describe is going against general advice/opinion (I do not think this has been explicitly stated anywhere, but it certainly has been the general consensus).

**Comment by kbevers** [comment]
This is clearly not going in 6.0 - is the issue still relevant after 6.0?
